spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3308/app_db?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: password

# docker run -td --name demo-mysql-app -p 3308:3306 -e MYSQL_ROOT_PASSWORD=password -e MYSQL_DATABASE=app_db -v $PWD/appdata:/var/lib/mysql mysql:8.0.22
